name: kimoi
description: A new Flutter project.
publish_to: 'yon30c'
version: 1.3.8

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  better_player_v3: ^0.0.2
  card_swiper: ^3.0.1
  dio: ^5.3.2
  firebase_analytics: ^10.5.0
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^5.7.2+3
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  fullscreen_window: ^1.0.4
  go_router: ^10.1.2
  html: ^0.15.4
  http: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  meta: ^1.9.1
  open_filex: ^4.3.2
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  wakelock_plus: ^1.1.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/knif.png
    - assets/icons/laughing.png
    - assets/icons/mystery.svg
    - assets/icons/watch-movie.png
    - assets/icons/triller.svg
    - assets/app_icon.webp
    - assets/app_icon_rounded.webp
    - .env
