name: kimoi
description: A new Flutter project.
publish_to: 'yon30c'
version: 1.2.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  better_player_v3: ^0.0.2
  card_swiper: ^3.0.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.4.0
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.5.0
  go_router: ^10.1.2
  html: ^0.15.4
  html_character_entities: ^1.0.0+1
  http: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  material_symbols_icons: ^4.2668.0
  meta: ^1.9.1
  open_filex: ^4.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  wakelock_plus: ^1.1.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/fast-forward.png
    - assets/icons/fullscreen.png
    - assets/icons/minimize.png
    - assets/icons/mute.png
    - assets/icons/play.png
    - assets/icons/pause.png
    - assets/icons/repeat.png
    - assets/icons/rewind.png
    - assets/icons/sound.png
    - assets/icons/picture-in-picture.png
    - assets/icons/exit_picture-in-picture.png
    - assets/icons/lock-screen.png
    - assets/icons/exit_lock-screen.png
    - assets/icons/fit.png
    - assets/jar-loading.gif
    - assets/loading4.gif
    - assets/images/
    - assets/icons/knif.png
    - assets/icons/laughing.png
    - assets/icons/watch-movie.png
    - assets/videos/loading.mp4
    - assets/app_icon.webp
    - assets/app_icon_rounded.webp
