// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlekV-z0yiMe3RgfIG1UttP4ScQDEke_o',
    appId: '1:980783454126:web:7dc1c2b4a8431ce2999a3f',
    messagingSenderId: '980783454126',
    projectId: 'kimoi-543c8',
    authDomain: 'kimoi-543c8.firebaseapp.com',
    storageBucket: 'kimoi-543c8.appspot.com',
    measurementId: 'G-PJYGPNWJ6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxi2NKzrBO5XAoeRTc4hIrkuZtdEB4ACc',
    appId: '1:980783454126:android:22a3cd59326490dc999a3f',
    messagingSenderId: '980783454126',
    projectId: 'kimoi-543c8',
    storageBucket: 'kimoi-543c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpvTR6j3W0_jp6bjwNw08_b-WNl1esTDU',
    appId: '1:980783454126:ios:1df3a593a1cf674b999a3f',
    messagingSenderId: '980783454126',
    projectId: 'kimoi-543c8',
    storageBucket: 'kimoi-543c8.appspot.com',
    iosBundleId: 'rd.ycd.kimoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpvTR6j3W0_jp6bjwNw08_b-WNl1esTDU',
    appId: '1:980783454126:ios:4850da0982a70280999a3f',
    messagingSenderId: '980783454126',
    projectId: 'kimoi-543c8',
    storageBucket: 'kimoi-543c8.appspot.com',
    iosBundleId: 'rd.ycd.kimoi.RunnerTests',
  );
}
